version: '3.8'

services:
  waiterapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waiterapp-api
    restart: always
    ports:
      - "${PORT:-3333}:${PORT:-3333}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3333}
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:password123@mongodb:27017/waiterapp?authSource=admin}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - waiterapp-network

  mongodb:
    image: mongo:7.0
    container_name: waiterapp-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: waiterapp
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - waiterapp-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: waiterapp-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - waiterapp-network

volumes:
  mongodb_data:
    driver: local

networks:
  waiterapp-network:
    driver: bridge
